export const partners = [
  {
    id: 1,
    name: "EA",
    content: "Lead Partner",
    officialUrl: "https://www.ea.com/en-gb/games/ea-sports-fc",
    logo: "/src/assets/partners/ea.png",
  },
  {
    id: 2,
    name: "Adobe",
    content: "Official Creativity Partner",
    officialUrl: "https://www.premierleague.com/en/adobe-hub",
    logo: "/src/assets/partners/ADB.webp",
  },
  {
    id: 3,
    name: "Barclays",
    content: "Official Bank",
    officialUrl: "https://home.barclays/",
    logo: "/src/assets/partners/Barclays_Sponsor.webp",
  },
  {
    id: 4,
    name: "Coca",
    content: "Official Soft Drink",
    officialUrl: "https://www.coca-cola.com/gb/en",
    logo: "/src/assets/partners/CocaCola_2526_Partner.webp",
  },
  {
    id: 5,
    name: "Guinness",
    content: "Official Beer",
    officialUrl: "https://www.guinness.com/en-gb",
    logo: "/src/assets/partners/guinness.svg",
  },
  {
    id: 6,
    name: "Microsoft",
    content: "Official Cloud & AI Partner",
    officialUrl: "https://unlocked.microsoft.com/premier-league/",
    logo: "/src/assets/partners/MSFT.png",
  },
  {
    id: 7,
    name: "Puma",
    content: "Official Ball",
    officialUrl: "https://about.puma.com/en",
    logo: "/src/assets/partners/puma_partner.png",
  },
  {
    id: 8,
    name: "Avery",
    content: "Official Licensee",
    officialUrl: "https://sport.averydennison.com/",
    logo: "/src/assets/partners/avery-dennison.svg",
  },
  {
    id: 9,
    name: "Football Manager",
    content: "Official Licensee",
    officialUrl: "https://www.footballmanager.com/",
    logo: "/src/assets/partners/football-manager.png",
  },
  {
    id: 10,
    name: "Rezzil",
    content: "Official Licensee",
    officialUrl: "https://rezzil.com/",
    logo: "/src/assets/partners/rezzil.png",
  },
  {
    id: 11,
    name: "Sorore",
    content: "Official Licensee",
    officialUrl: "https://sorare.com/",
    logo: "/src/assets/partners/sorare.png",
  },
  {
    id: 12,
    name: "Topps",
    content: "Official Licensee",
    officialUrl: "https://uk.topps.com/",
    logo: "/src/assets/partners/Topps_2526_Partner.webp",
  },
];
